pI'm sorry, but an uncaught exception occurred.

While running game code:
IOError: [Errno 2] No such file or directory: u'/Users/ginnyn/Desktop/Renpy Projects/user-interface-game/game/saves/persistent.1600531552.tmp'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Applications/renpy-7.3.5-sdk/renpy/bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "/Applications/renpy-7.3.5-sdk/renpy/main.py", line 581, in main
    renpy.persistent.update(True)
  File "/Applications/renpy-7.3.5-sdk/renpy/persistent.py", line 391, in update
    save()
  File "/Applications/renpy-7.3.5-sdk/renpy/persistent.py", line 407, in save
    renpy.loadsave.location.save_persistent(data)
  File "/Applications/renpy-7.3.5-sdk/renpy/savelocation.py", line 490, in save_persistent
    l.save_persistent(data)
  File "/Applications/renpy-7.3.5-sdk/renpy/savelocation.py", line 347, in save_persistent
    with open(fn_tmp, "wb") as f:
IOError: [Errno 2] No such file or directory: u'/Users/ginnyn/Desktop/Renpy Projects/user-interface-game/game/saves/persistent.1600531552.tmp'

Darwin-19.6.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
User Interface 0.4.1
Sat Sep 19 14:12:25 2020
